### ISSUE TITLE
Upgrade Fern + TS generator

### ISSUE THREAD

**Issue by dsinghvi** [flipt-io/flipt-api#47]
```
Did you mean to provide the overwrite option? A source file already exists at the provided file path: /resources/auth/client/Client.ts
```
@markphelps @GeorgeMac see that you are hitting this issue in [CI](https://github.com/flipt-io/flipt-api/actions/runs/4243918791/jobs/7377303437). 

If you upgrade fern by running `fern upgrade` and also upgrade the TS generator to 0.1.7 then things should work. 

[Discord Thread](https://discord.com/channels/988611740499574794/988611741476859916/1077976552735768637)

**Comment by markphelps** [comment]
Fixed in #48
